#!/usr/bin/env bash
#Preprocessing the data
if [[ -z $1 ]]
then
	1>&2 echo "Error Details: You are missing arguments!"
	exit 2
elif [[ ! -f $1 ]]
then
	1>&2 echo "Error Details: Failed to find the file $1"
	exit 1
fi


